version: '3'
services:

  postgresql:
    image: postgres
    container_name: lessons
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=lessons
      - POSTGRES_PASSWORD=lessons
      - POSTGRES_DATABASE=lessons
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lessons
    ports:
      - "6379:6379"




